config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "application#home"

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  get '/playlists/user_playlists', to: 'playlists#user_playlists', as: 'user_playlists'
  get '/songs/user_songs', to: 'songs#user_songs'

  resources :songs

  resources :playlists do
    resources :songs, only: [:show, :new, :edit]
  end

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :songs
    has_many :users, through: :songs

    validates :title, presence: true

    def songs_attributes=(songs_attributes)
        songs_attributes.values.each do |song_attribute|
            if song_attribute[:title]!=""
                song=Song.find_or_create_by(song_attribute)
                self.songs << song
            end
        end
    end

    def song_count
        self.songs.count
    end

end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :playlist
    belongs_to :user

    accepts_nested_attributes_for :playlist, reject_if: proc{|attr| attr[:title].blank?}

    validates :title, presence: true
    
    scope :by_genre, ->(genre) { where("genre = ?", genre) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :songs
  has_many :playlists, through: :songs
  

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid:auth.uid).first_or_create do |user|
        user.provider=auth.provider
        user.username=auth.info.name
        user.uid=auth.uid
        user.email=auth.info.email
        user.password=Devise.friendly_token[0,20]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    skip_before_action :require_login, if: :devise_controller?
            
    def home
    end

    private

        def require_login
            unless user_signed_in?
                flash[:error] = "You must be logged in to access this page"
                redirect_to new_user_session_path
            end
        end
    
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
        user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect user
    end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  
  def user_playlists
    @playlists=current_user.playlists.uniq
  end

  def index
    @playlists=Playlist.all
  end

  def show
    @playlist=Playlist.find_by(id: params[:id])
  end

  def new
      @playlist=current_user.playlists.build
  end

  def create
      verify_id
      @playlist=current_user.playlists.build(playlist_params)
      if @playlist.save
        redirect_to @playlist
      else
       render :new
      end
  end

  def edit
    @playlist=current_user.playlists.find_by(id: params[:id])
  end

  def update
    verify_id
    @playlist=current_user.playlists.find_by(id: params[:id])
    if @playlist.update(update_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  def destroy
    @playlist=current_user.playlists.find_by(id: params[:id])
    if @playlist
      @playlist.destroy
    end
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:title, :description, :user_id, song_ids:[], songs_attributes: [:title, :user_id, :playlist_id])
  end

  def update_params
    params.require(:playlist).permit(:title, :description)
  end

  def verify_id
    if params[:user_id]!= current_user.id
      params[:user_id]=current_user.id
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    # skip_before_action :require_login, if: :devise_controller?

    private

    def signup_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # before_action :require_login
  
  def index
    # binding.pry
    if params[:search]
      @songs=Song.by_genre(params[:search])
    else
      @songs=Song.all
    end
  end

  def user_songs
    @songs=current_user.songs
  end

  def show
    @song=Song.find_by(id: params[:id])
  end

  def new
      @song=current_user.songs.build
  end

  def create  
      @song=current_user.songs.build(song_params)
        if @song.save
          redirect_to @song
        else
          render :new
        end
  end

  def edit
      @song=current_user.songs.find_by(id: params[:id])
  end

  def update
      @song=current_user.songs.find_by(id: params[:id])
      if @song.update(song_params)
        redirect_to @song
      else
        render :edit
      end
  end

  def destroy
    @song=current_user.songs.find_by(id: params[:id])
    if @song
      @song.destroy
    end
    redirect_to songs_path
  end

 private
  def song_params
    params.require(:song).permit(:title, :artist, :album, :genre, :web_address, :user_id, :playlist_id, playlist_attributes: [:title])
  end

  def verify_id
    if params[:user_id]!= current_user.id
      params[:user_id]=current_user.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/application/home.html.erb
<h1>Welcome to the Playlist App</h1>

<h2>Get Started</h2>
<%= link_to 'Create a New Playlist', new_playlist_path %> <br>
<%= link_to 'Create a New Song', new_song_path %>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <% if !user_signed_in? %>
            <li><%= link_to 'Signup', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% else %>
            <p> 
            Welcome <%= current_user.email %>!
            <br><%= link_to 'Home', root_path %>
            <br><%= link_to 'Logout', destroy_user_session_path, method:'delete' %>
            <br><%= link_to 'All Playlists', playlists_path %>
            <br><%= link_to 'Your Playlists', user_playlists_path %>
            <br><%= link_to 'All Songs', songs_path %>
            <br><%= link_to 'Your Songs', '/songs/user_songs'%>
            </p>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlaylistProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render '/layouts/nav'%>
    <%= yield %>
  </body>
</html>

app/views/playlists/_playlist_form.html.erb
<%= form_for @playlist do |f| %>

<%if @playlist.errors%>
    <% @playlist.errors.full_messages.each do |full_message|%>
        <%= full_message %>
    <%end%>
<%end%>
<br>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.label :songs %>
    <%= f.collection_select :song_ids, current_user.songs , :id, :title, include_blank: "Select Song" %>
    <br>
    <%= f.fields_for :songs, @playlist.songs.build do |songs_fields|%>
        <%= songs_fields.text_field :title %>
        <%= songs_fields.hidden_field :user_id, value: current_user.id %>
    <% end %>

    <%= f.submit%>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<% if !@playlist %>

    <h3>Sorry, you do not have access to this action.</h3>

<% else %>
    <%= form_for @playlist do |f| %>

        <%if @playlist.errors%>
            <% @playlist.errors.full_messages.each do |full_message|%>
                <%= full_message %>
            <%end%>
        <%end%>
    <br>

        <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <%= f.label :description %>
        <%= f.text_area :description %>

        <%= f.submit%>
    <% end %>

<% end %>

app/views/playlists/index.html.erb
<h1>Playlists</h1>

<ul>
<% @playlists.each do |playlist| %>
   <p> <%= link_to playlist.title, playlist %> - <%= playlist.song_count %> songs</p>
<%end%>
</ul>

<br>
<%= link_to 'New Playlist', new_playlist_path %>
<br>
<br>
<br>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'playlist_form' %>

app/views/playlists/show.html.erb
<h1><%= @playlist.title %></h1>
<h4><%= @playlist.description %></h4>

<p>
    <% @playlist.songs.each do |song| %>
        <%= link_to song.title, playlist_song_path(@playlist, song) %>
        <br>
    <% end %>
</p>
<br>
<%= link_to 'Edit Playlist', edit_playlist_path %>
<br>
<%= link_to 'Add Song', new_playlist_song_path(@playlist) %>
<br>
<%= link_to 'Delete Playlist', playlist_path(@playlist), method:'delete' %>

app/views/playlists/user_playlists.html.erb
<h1>Playlists</h1>

<ul>
<% @playlists.each do |playlist| %>
   <p> <%= link_to playlist.title, playlist %> - <%= playlist.song_count %> songs</p>
<%end%>
</ul>

<br>
<%= link_to 'New Playlist', new_playlist_path %>

app/views/songs/_song_form.html.erb
<%= form_for @song do |f| %>

<%if @song.errors%>
    <% @song.errors.full_messages.each do |full_message|%>
        <%= full_message %>
    <%end%>
<%end%>

<br>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br>
    <%= f.label :album %>
    <%= f.text_field :album %>
    <br>
    <%= f.label :web_address %>
    <%= f.text_field :web_address %>
    <br>
    <%= f.label :playlist %>
    <%= f.collection_select :playlist_id, Playlist.all, :id, :title, include_blank: "Select Playlist"%>
    <br>
    <%= f.fields_for :playlist, @song.build_playlist do |playlist_fields|%>
        <%= playlist_fields.text_field :title%>
    <% end %>

    <%= f.submit%>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<% if !@song %>

    <h3>Sorry, you do not have access to this action.</h3>

<% else %>

    <%= render 'song_form' %>

<% end %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<ul>
<% @songs.each do |song| %>
   <p> <%= link_to song.title, song%> 
    <%if song.artist%>
        by <%= song.artist %></p>
    <% end %>
<%end%>
</ul>

<%= link_to 'New Song', new_song_path %>
<br>
<%= form_tag '/songs', method: :get %>
<%= label_tag 'Search by genre'%>
<%= text_field_tag 'search'  %>
<%= submit_tag 'Search'%>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'song_form' %>

app/views/songs/show.html.erb
<h1><%= @song.title%></h1>

<p>
    Artist: <%= @song.artist %>
    <br>
    Genre: <%= @song.genre %>
    <br>
    Album: <%= @song.album %>
    <br>
    <%#binding.pry%>
    Link: <%= link_to @song.web_address, @song.web_address if @song.web_address%>
    <br>
    <br>
    Playlist: <%= link_to @song.playlist.title, playlist_path(@song.playlist) if @song.playlist%>
</p>
<br>
<%= link_to 'Edit Song', edit_song_path %>
<br>
<%= link_to 'Delete Song', song_path(@song), method: 'delete' %>

app/views/songs/user_songs.html.erb
<h1>Songs</h1>

<ul>
<% @songs.each do |song| %>
   <p> <%= link_to song.title, song%> 
    <%if song.artist%>
        by <%= song.artist %></p>
    <% end %>
<%end%>
</ul>

<%= link_to 'New Song', new_song_path %>